version: 1
apps:
  - name: claude-usage-calculator
    description: Interactive Claude Usage and Cost Calculator for Bedrock pricing analysis
    start_command: python -m streamlit run app.py --server.port 8080 --server.address 0.0.0.0